# Generated by Django 5.2.2 on 2026-06-10 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAIL', 'Failed Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PROFILE_UPDATE', 'Profile Update'), ('RESERVATION_CREATE', 'Reservation Created'), ('RESERVATION_EDIT', 'Reservation Edited'), ('RESERVATION_CANCEL', 'Reservation Cancelled'), ('ROOM_CREATE', 'Room Created'), ('ROOM_EDIT', 'Room Edited')], max_length=30)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
